package br.com.cocodonto.modelo.dao;

import java.sql.Connection;
import java.sql.SQLException;

import br.com.cocodonto.framework.dao.DaoHelper;
import br.com.cocodonto.modelo.entidade.Endereco;

public class EnderecoDao {
	
	private DaoHelper daoHelper;
	
	public EnderecoDao() {
		daoHelper = new DaoHelper();
	}

	public void inserir (Endereco endereco) {
		
		long id = 0l;
		try {
			//daoHelper.beginTransaction();
			
			id = daoHelper.preparedUpdateWithAutoGeneratedKeys( INSERT_ENDERECO_STMT 
				   										     , endereco.getEndereco()
													 	     , endereco.getCidade()
														     , endereco.getCep()
														     , endereco.getBairro());
			endereco.setId(id);
			//daoHelper.endTransaction();
		} catch (SQLException e) {
			daoHelper.rollbackTransaction();
		} 
		
		
	}
	
	private static final String INSERT_ENDERECO_STMT = 	"INSERT INTO ENDERECO (ENDERECO,CIDADE,CEP,BAIRRO) VALUES (?,?,?,?)";

}
